### ISSUE TITLE
token-js: getOrCreateAssociatedTokenAccount  Fails when there's no associated account

### ISSUE THREAD

**Issue by edgework** [solana-labs/solana-program-library#4718] opened 2023-07-06 17:55 UTC
The "create" part of getOrCreateAssociatedTokenAccount  throws a TokenAccountNotFoundError when the TA  doesn't exist  but it does create the account.  In order to get around this the process must be restarted.  Evidently the spl-token module is storing some state.  On the next process run, the previously created TA is found and returned.

I know there's another open issue (about a year old now) that refers to TokenAccountNotFoundError being thrown for other errors but this is (or should be) different and addressed.

**Comment by kasuba97** [comment] 2023-07-27 09:27
Am getting the same error too.

Tried reinstalling dependencies but still get the error.

**Comment by kasuba97** [comment] 2023-08-26 21:32
> The "create" part of getOrCreateAssociatedTokenAccount throws a TokenAccountNotFoundError when the TA doesn't exist but it does create the account. In order to get around this the process must be restarted. Evidently the spl-token module is storing some state. On the next process run, the previously created TA is found and returned.
> 
> I know there's another open issue (about a year old now) that refers to TokenAccountNotFoundError being thrown for other errors but this is (or should be) different and addressed.

hey I think the error was being caused due to the code trying to access the token account before its on chain. you can fix this by add the commitment object as a parameter to the Connection function 
`const conn = new web3.Connection(web3.ClusterApiUrl(<net>),{Commitment:'confirmed'})`

**Comment by joncinque** [comment] 2023-08-29 10:52
Ah ok, shall I close this issue then?

**Comment by kasuba97** [comment] 2023-08-29 11:33
sure

**Closed** 2023-08-29 11:34 UTC
