### ISSUE TITLE
Error when execute command "cargo install spl-token-cli"

### ISSUE THREAD

**Issue by Salasie** [solana-labs/solana-program-library#5737] opened 2023-11-07 08:08 UTC
When I execute next command:

cargo install spl-token-cli

I have the next error:

```
   Compiling spl-type-length-value v0.3.0
error[E0432]: unresolved import `index_list::Index`
 --> /home/salasie/.cargo/registry/src/index.crates.io-6f17d22bba15001f/solana-runtime-1.16.16/src/read_only_accounts_cache.rs:5:18
  |
5 |     index_list::{Index, IndexList},
  |                  ^^^^^ no `Index` in the root
  |
  = help: consider importing one of these items instead:
          std::ops::Index
          core::ops::Index

   Compiling spl-tlv-account-resolution v0.4.0
   Compiling spl-token-metadata-interface v0.2.0
   Compiling spl-transfer-hook-interface v0.3.0
   Compiling spl-token-2022 v0.9.0
For more information about this error, try `rustc --explain E0432`.
error: could not compile `solana-runtime` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `spl-token-cli v3.2.0`, intermediate artifacts can be found at `/tmp/cargo-installBzD66q`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

Previusly I execute:

sudo apt-get update
sudo apt-get install -y pkg-config build-essential libudev-dev
sudo apt-get install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang cmake make libprotobuf-dev protobuf-compiler

Versions:

rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.73.0 (cc66ad468 2023-10-03)`

rustc --version
rustc 1.73.0 (cc66ad468 2023-10-03)

cargo --version
cargo 1.73.0 (9c4383fb5 2023-08-26)

**Comment by buffalojoec** [comment] 2023-11-07 17:16
Hello there, I can reproduce your problem! Seems to be happening when I try to install the CLI as well. I'll dig around and circle back.

**Comment by Salasie** [comment] 2023-11-07 21:40
HI

I see it in--> https://github.com/solana-labs/solana/blob/master/Cargo.toml#L219

use index_list version 0.2.7 --> in this version Index exist https://docs.rs/index_list/0.2.7/index_list/struct.Index.html

but, they have a new version to index_list 0.2.10 --> https://docs.rs/index_list/0.2.10/index_list/index.html

in this case, you try to use next version --> 0.2.10, but de "field" Index doesn't exist

how you can resolve this:

use specific version --> https://github.com/solana-labs/solana/blob/master/Cargo.toml#L219 change with --> index_list = "=0.2.7"

or wait that  index_list owners change that version! ( they should have created a mayor version, for example 0.3.0 with that changes and delete 0.2.10)

**Comment by Salasie** [comment] 2023-11-07 22:11
I just created the following pr --> https://github.com/solana-labs/solana/pull/33980

**Comment by Salasie** [comment] 2023-11-07 23:25
problem resolved!

Installed package `spl-token-cli v3.2.0` (executable `spl-token`)

https://github.com/Fairglow/index-list/issues/5

**Comment by joncinque** [comment] 2023-11-07 23:50
That's great! Closing the issue

**Closed by joncinque** 2023-11-07 23:50 UTC

**Comment by buffalojoec** [comment] 2023-11-08 08:24
Awesome thanks for that! Looks like we're all set now.
