### ISSUE TITLE
Numerical error in `ui_amount_to_amount`

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana-program-library#431] opened 2020-09-11 15:48 UTC
Numerical error when casting from f64 to u64. If the ui_amount is a relatively large value, in this case, 10^11 and the decimals parameter has the default value of 9, the "expected" result would be 10^20. However, the actual result is u64::MAX. Should probably have a check confirming that the equation will fit in an u64.

**Comment by mvines** [comment] 2020-09-14 18:39
Duplicate of https://github.com/solana-labs/solana-program-library/issues/432

**Closed by mvines** 2020-09-14 18:39 UTC
