### ISSUE TITLE
"custom program error: 0xc" regression in createMint() on spl-token@0.3.5 and later (spl-token@0.3.4 is fine)

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana-program-library#4051] opened 2023-02-14 15:49 UTC
**Minimal reproduction case attached at https://github.com/mikemaccana/bug-reproduction**

The following code works fine on 0.3.4:

```
import { Connection, Keypair } from "@solana/web3.js";
import { createMint } from "@solana/spl-token";
import { log } from "console";

const main = async () => {
  const connection = new Connection("http://127.0.0.1:8899");
  const testMintAuthority = new Keypair();
  var airdropSignature = await connection.requestAirdrop(
    testMintAuthority.publicKey,
    1_000_000_000
  );

  const latestBlockHash = await connection.getLatestBlockhash();

  // Wait for airdrop confirmation
  await connection.confirmTransaction({
    blockhash: latestBlockHash.blockhash,
    lastValidBlockHeight: latestBlockHash.lastValidBlockHeight,
    signature: airdropSignature,
  });

  // Fails with error c, aaka error 12 at
  // https://github.com/solana-labs/solana-program-library/blob/master/token/program/src/error.rs
  // 'Invalid instruction'
  const mintAccountPublicKey = await createMint(
    connection,
    testMintAuthority,
    testMintAuthority.publicKey,
    null, // Don't bother with a freeze address
    0
  );

  log(`mintAccountPublicKey:`, mintAccountPublicKey.toBase58());
};

main();

```

Results on 0.3.4:

```
$ npx esrun runme.ts
mintAccountPublicKey: HJrvms1ufZFKHPcZWUfXiZffumRd6F855Wcv2oDWCdwQ
```

And will fail on 0.3.5 or 0.3.7.

```
$ npx esrun runme.ts
/home/mike/Code/portal/bug-reproduction/node_modules/@solana/web3.js/lib/index.cjs.js:9820
      throw new SendTransactionError('failed to send transaction: ' + res.error.message, logs);
            ^

SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 1: custom program error: 0xc
    at Connection.sendEncodedTransaction (/home/mike/Code/portal/bug-reproduction/node_modules/@solana/web3.js/lib/index.cjs.js:9820:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.sendRawTransaction (/home/mike/Code/portal/bug-reproduction/node_modules/@solana/web3.js/lib/index.cjs.js:9777:20)
    at async Connection.sendTransaction (/home/mike/Code/portal/bug-reproduction/node_modules/@solana/web3.js/lib/index.cjs.js:9767:12)
    at async sendAndConfirmTransaction (/home/mike/Code/portal/bug-reproduction/node_modules/@solana/web3.js/lib/index.cjs.js:2265:21)
    at async createMint (file:///home/mike/Code/portal/bug-reproduction/node_modules/@solana/spl-token/lib/esm/actions/createMint.js:28:5)
    at async main (file:///home/mike/Code/portal/bug-reproduction/[eval1]:20:32) {
  logs: [
    'Program 11111111111111111111111111111111 invoke [1]',
    'Program 11111111111111111111111111111111 success',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]',
    'Program log: Error: Invalid instruction',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 796 of 400000 compute units',
    'Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: custom program error: 0xc'
  ]
}
```

**Comment by joncinque** [comment] 2023-02-15 00:42
Sorry, I can't reproduce this, either on master, 0.3.7, or 0.3.5. This is both using your reproduction, and changing a local test to look just like your bug reproduction.

I did make a change to your repro:

```
  const connection = new Connection("http://127.0.0.1:8899");
```

to 

```
  const connection = new Connection("http://127.0.0.1:8899", "confirmed");
```

To speed things up, but I don't think that would make a difference. What version of the CLI are you using for your local test validator? Maybe that's making a difference. I tested with 1.13.6, currently the supermajority on mainnet, to be sure.

**Comment by mikemaccana** [comment] 2023-02-15 11:36
Thanks @joncinque that actually helps a lot. Changing `confirmation` didn't fix it but I think we're onto the right track - I wonder if the version of the spl-token on-chain app in `solana-test-validator` needs to be upgraded for the new `spl-token` - that fits along with having a program error.  **I really wish they would tell us this when `spl-token` has new releases** but h, well, I can send a PR to the docs if this fixes it.

> What version of the CLI are you using for your local test validator? 

```
$ solana-test-validator --version
solana-test-validator 1.9.30 (src:30e47c2b; feat:462418899)
```

Trying an upgrade now,

**Comment by joncinque** [comment] 2023-02-15 11:48
Typically, the recommendation is to run at least the same version as mainnet for your local tools, and I'd even recommend running the same as testnet to be ahead of everything.

We don't backport program changes to all earlier versions, since new programs may use features not supported by very old clusters. Also, it's just not worth the hassle.

Otherwise, you can find spl-token releases at https://github.com/solana-labs/solana-program-library/releases?q=token&expanded=true

**Comment by mikemaccana** [comment] 2023-02-15 11:55
@joncinque confirmed, updating my local validator allows me to use the newer version of `@solana/spl-token`! I'll let the people on Solana Stack Exchange know this fixes it.

How can I see the versions - of Solana and each on-chain program - on `mainnet-beta` or `testnet`? Feel free to point me to docs if they exist. Thanks again for your help.

**Comment by joncinque** [comment] 2023-02-15 12:05
The GitHub releases page https://github.com/solana-labs/solana-program-library/releases has the latest release for each program. For example, https://github.com/solana-labs/solana-program-library/releases/tag/token-v3.5.0 is the latest spl-token release.

And for Solana version on clusters, you can use `solana validators`. For example, here's mainnet currently:

```
Stake By Version:
1.13.1   -    0 current validators ( 0.00%),   1 delinquent validators ( 0.00%)
1.13.3   -   12 current validators ( 0.36%)
1.13.4   -   10 current validators ( 0.53%),   1 delinquent validators ( 0.02%)
1.13.5   -  723 current validators (54.54%),  20 delinquent validators ( 0.04%)
1.13.6   - 1199 current validators (32.69%),  36 delinquent validators ( 0.28%)
1.13.7   -    1 current validators ( 0.13%)
1.14.10  -    1 current validators ( 0.01%)
1.14.11  -    1 current validators ( 0.00%)
1.14.13  -    4 current validators ( 0.05%),   4 delinquent validators ( 0.00%)
1.14.15  -  436 current validators (10.37%),  26 delinquent validators ( 0.26%)
1.14.5   -    0 current validators ( 0.00%),   5 delinquent validators ( 0.09%)
1.15.0   -    1 current validators ( 0.02%)
1.15.1   -    0 current validators ( 0.00%),   1 delinquent validators ( 0.02%)
1.15.2   -    0 current validators ( 0.00%),   1 delinquent validators ( 0.01%)
1.15.3   -    0 current validators ( 0.00%),   1 delinquent validators ( 0.00%)
1.8.14   -    0 current validators ( 0.00%),   1 delinquent validators ( 0.00%)
1.9.12   -    0 current validators ( 0.00%),   1 delinquent validators ( 0.00%)
unknown  -    1 current validators ( 0.00%), 614 delinquent validators ( 0.56%)
```

Since everything is fixed, I'll close this issue

**Closed by joncinque** 2023-02-15 12:05 UTC

**Comment by mikemaccana** [comment] 2023-02-15 12:29
Thanks @joncinque . I've updated https://solana.stackexchange.com/questions/4933/solana-spl-token-createmint-is-broken-with-custom-program-error-0xc-invali/5806#5806 to show people how to check if their local validator is out of date too.  

Re: https://github.com/solana-labs/solana-program-library/releases - when a new SPL is released, can I assume it's running in mainnet? I was hoping for something like `solana program show <address>` to see a version number. But maybe I can just `solana program dump` the programs I need locally every so often to make sure they're recent.

**Comment by joncinque** [comment] 2023-02-15 12:45
> Re: https://github.com/solana-labs/solana-program-library/releases - when a new SPL is released, can I assume it's running in mainnet

Typically yes, although now that I remember, spl-token 3.5.0 wasn't released to mainnet, since the change there fixes a validator-level problem on instruction decoding, and not a program issue.

If you look at the release notes for 3.4.0, it shows you how to perform a verifiable build and check whatever's on-chain https://github.com/solana-labs/solana-program-library/releases/tag/token-v3.4.0 -- you can run that from the tag. All deployments use anchor verifiable builds, so that anyone can reproduce it. Typically the most recently deployed program will provide those instructions.

**Comment by joncinque** [comment] 2023-02-15 13:03
Actually, we did just add audit information for programs at https://github.com/solana-labs/solana-program-library#audits -- and you can assume that we don't deploy something that's unaudited to mainnet.
