### ISSUE TITLE
Incorrect Obligations structure length calculation

### ISSUE THREAD

**Issue by kuznetsov-m** [solana-labs/solana-program-library#1801] opened 2021-05-26 10:52 UTC
# Problem
Into file [obligation.rs](https://github.com/solana-labs/solana-program-library/blob/c3657e5568473fa8acd739f8d74cc80ad7de360d/token-lending/program/src/state/obligation.rs#L327) Decimal size is 16. It is incorect. Size shuld be 3 * 8 = 24 (3 x 64-bit words)

Decimal definition [decimal.rs](https://github.com/solana-labs/solana-program-library/blob/ecc25f7d268b6b6396d082aa485fa0e2238427a4/token-lending/program/src/math/decimal.rs#L28)
```
// U192 with 192 bits consisting of 3 x 64-bit words
construct_uint! {
    pub struct U192(3);
}

/// Large decimal values, precise to 18 digits
#[derive(Clone, Copy, Debug, Default, PartialEq, PartialOrd, Eq, Ord)]
pub struct Decimal(pub U192);
```

# Solution
[obligation.rs](https://github.com/solana-labs/solana-program-library/blob/c3657e5568473fa8acd739f8d74cc80ad7de360d/token-lending/program/src/state/obligation.rs#L327) 
```
/// Obligation collateral state
#[derive(Clone, Debug, Default, PartialEq)]
pub struct ObligationCollateral {
    /// Reserve collateral is deposited to
    pub deposit_reserve: Pubkey,
    /// Amount of collateral deposited
    pub deposited_amount: u64,
    /// Collateral market value in quote currency
    pub market_value: Decimal,
}

/// Lending market obligation state
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Obligation {
    /// Version of the struct
    pub version: u8,
    /// Last update to collateral, liquidity, or their market values
    pub last_update: LastUpdate,
    /// Lending market address
    pub lending_market: Pubkey,
    /// Owner authority which can borrow liquidity
    pub owner: Pubkey,
    /// Deposited collateral for the obligation, unique by deposit reserve address
    pub deposits: Vec<ObligationCollateral>,
    /// Borrowed liquidity for the obligation, unique by borrow reserve address
    pub borrows: Vec<ObligationLiquidity>,
    /// Market value of deposits
    pub deposited_value: Decimal,
    /// Market value of borrows
    pub borrowed_value: Decimal,
    /// The maximum borrow value at the weighted average loan to value ratio
    pub allowed_borrow_value: Decimal,
    /// The dangerous borrow value at the weighted average liquidation threshold
    pub unhealthy_borrow_value: Decimal,
}

const OBLIGATION_COLLATERAL_LEN: usize = 64; // 32 + 8 + 24
const OBLIGATION_LIQUIDITY_LEN: usize = 104; // 32 + 24 + 24 + 24
const OBLIGATION_LEN: usize = 1140; // 1 + 8 + 1 + 32 + 32 + 24 + 24 + 24 + 24 + 1 + 1 + (64 * 1) + (104 * 9)
```

Perhaps it is worth replacing manual calculation with a call to `std::mem::size_of::<Decimal>()`

**Comment by kuznetsov-m** [comment] 2021-05-26 10:55
@jordansexton, excuse me, what you think about?

**Comment by jordansexton** [comment] 2021-05-27 15:45
It looks like the 16 byte length comes from here: https://github.com/solana-labs/solana-program-library/blob/5e320ba9768cca8ca751a4db26786ed13bb0d40f/token-lending/program/src/state/mod.rs#L67-L76

I'm not very familiar with these. @jstarry could you explain how this works? Does it accept some loss of precision?

**Comment by jstarry** [comment] 2021-05-27 17:15
Shouldn't be any loss of precision, all values fit inside u128 but u192 is used for arithmetic to prevent overflows during calculations

**Comment by jordansexton** [comment] 2021-06-08 01:31
Closing since it seems like it's working as designed, but please reopen if this didn't cover the issue.

**Closed by jordansexton** 2021-06-08 01:31 UTC
