### ISSUE TITLE
example: Link source needed to system program instruction

### ISSUE THREAD

**Issue by Mystiik** [solana-labs/solana-program-library#2243] opened 2021-08-09 18:48 UTC
https://github.com/solana-labs/solana-program-library/blob/31603ed3753d5d329ce8ccb57e3d43b0cb2eca38/examples/c/src/cross-program-invocation/cross-program-invocation.c#L36

Could you pllease add a link to the source to know all allocate instruction enum values ?

**Comment by SUMEETRM** [comment] 2022-07-05 08:25
@joncinque could you explain what needs to be done to fix this? Thanks

**Comment by joncinque** [comment] 2022-07-06 20:42
Absolutely, the issue is that the enum values are not explained or exposed anywhere in this file.  For example, how are we supposed to know that `8` means `allocate`?  We need to look at where the system instructions are defined, at https://github.com/solana-labs/solana/blob/master/sdk/program/src/system_instruction.rs#L156, and count up from 0, where 0 is CreateAccount, 1 is Assign, all the way up to 8 = Allocate.  So you can at least provide the link to where the instructions are defined.

**Comment by joncinque** [comment] 2022-08-09 15:11
Fixed with #3439

**Closed by joncinque** 2022-08-09 15:11 UTC
Labels: good first issue
