### ISSUE TITLE
could not find `spl-token-lending-cli` in registry `crates-io` with version `*`

### ISSUE THREAD

**Issue by clayonss** [solana-labs/solana-program-library#2219] opened 2021-08-05 07:41 UTC
cargo install spl-token-lending-cli

**Comment by joncinque** [comment] 2021-08-17 20:00
Looks like the crate hasn't been released yet.  Maybe @jordansexton has a plan for releasing the CLI crate at some point?

**Comment by jordansexton** [comment] 2021-08-18 20:57
Ah, I'll do this. I've never released a crate before... so I forgot to learn how!

**Comment by BlockchainSavingsNonprofitBank** [comment] 2022-01-26 21:34
sorry, but whats the --path ?

**Comment by MedadRufus** [comment] 2022-01-26 22:51
The path is the local directory(`solana-program-library/token-lending/cli`). Note the dot at the end of the command `$ cargo install --path .`

**Comment by BlockchainSavingsNonprofitBank** [comment] 2022-01-27 00:20
Caused by:
  unable to get packages from source

Caused by:
  failed to parse manifest at `/home/raymond/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-program-1.9.5/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest

**Comment by joncinque** [comment] 2022-05-11 22:32
https://crates.io/crates/spl-token-lending-cli/ is available on crates.io, closing this issue

**Closed by joncinque** 2022-05-11 22:32 UTC
