### ISSUE TITLE
Migrate to @solana/buffer-layout

### ISSUE THREAD

**Issue by israelidanny** [solana-labs/solana-program-library#2534] opened 2021-10-20 14:24 UTC
The `buffer-layout` package used here as a dependency lacks proper typing, which causes issues with downstream libraries depending on the token program TypeScript code.

Solana Labs maintains a buffer-layout implementation with types already:
https://github.com/solana-labs/buffer-layout

I suggest to change the dependency to that implementation.

**Comment by israelidanny** [comment] 2021-11-18 15:09
@jstarry alright. I'm picking this up then. Will submit a PR for your review ASAP.

**Comment by jstarry** [comment] 2021-11-18 15:20
> @jstarry alright. I'm picking this up then. Will submit a PR for your review ASAP.

Awesome, thanks @israelidanny!

**Comment by joncinque** [comment] 2021-12-09 15:27
Reopening since swap and lending still use the old buffer-layout

**Comment by israelidanny** [comment] 2021-12-13 15:12
@joncinque @jstarry I added this PR:
https://github.com/solana-labs/solana-program-library/pull/2634

It has a couple of caveats (generics missing in current typing e.t.c) but pushes us one step closer to making this tidy

**Comment by zkhalapyan** [comment] 2022-01-07 04:42
+1, hope the PR lands soon :)

**Comment by israelidanny** [comment] 2022-01-07 12:18
Not sure what this is being held back by! The PR is ready:
https://github.com/solana-labs/solana-program-library/pull/2634

And I'm more than happy to change anything if there are issues with the PR.

**Comment by jordansexton** [comment] 2022-01-07 19:57
Just being held back by review at this point :) I'll try to get to it soon.

**Comment by alexgb0** [comment] 2022-01-10 15:08
There is any way to quick fix it in the meanwhile the issue is still being fixed?

**Comment by zkhalapyan** [comment] 2022-01-10 23:10
I am not proud of this, but the only way I could unblock myself is by setting `"noImplicitAny": false` in `tscconfig.json`:

```js
➜  wonka git:(main) ✗ cat tsconfig.json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "esModuleInterop": true,
    "declaration": true,
    "outDir": "./lib",
    "strict": true,
    "noImplicitAny": false,
  },
  "include": ["src"],
  "exclude": ["node_modules", "**/__tests__/*"]
}
```

**Comment by jordansexton** [comment] 2022-01-15 05:19
I reviewed #2634 and have one small question, but I plan to merge tomorrow.

**Comment by FernandoTBarros** [comment] 2022-03-06 18:15
I'm having the same problem. Is there anything I could help to fix this?

**Comment by israelidanny** [comment] 2022-03-08 16:52
@jordansexton any luck? This has been stuck for ages ...

**Comment by gaurav-12** [comment] 2022-03-26 07:22
Still facing the issue on React Project, anyone, any suggestions?
Using following versions:
```
"@solana/spl-token": "^0.2.0",
"@solana/web3.js": "^1.36.0",
```

![image](https://user-images.githubusercontent.com/37019191/160229289-09ed66b7-6866-4a30-a415-78cf953561d6.png)

**Comment by israelidanny** [comment] 2022-03-26 09:54
Yo, @jordansexton , what's going on with merging this?

**Comment by jordansexton** [comment] 2022-03-26 15:53
Just been busy with other things 🙂 I'll take a look this weekend.

**Comment by jordansexton** [comment] 2022-03-27 04:01
https://github.com/solana-labs/solana-program-library/pull/2634 has been merged. Thanks for your hard work on this, and sorry for the delay. We'll probably need to release some updated NPM packages, yeah?

**Closed** 2022-03-27 04:01 UTC

**Comment by nurav97** [comment] 2022-03-28 09:04
when will the package be released this is breaking the metaplex/js lib as it uses the @solana/spl-token lib

**Comment by israelidanny** [comment] 2022-03-28 13:57
@jordansexton yes, I would imagine so. I think this qualifies as a minor version bump (no API changes, just typing)?

**Comment by nurav97** [comment] 2022-03-30 07:00
when can we expect this to release we are stuck on this issue for days ?

**Comment by jordansexton** [comment] 2022-03-30 17:21
Thanks for your patience. We are currently trying to figure out whether these packages need to be released as a major/breaking version, because it causes problems if someone has `buffer-layout` and `@solana/buffer-layout` in their dependencies. We'll sort this out soon! cc @steveluscher

**Comment by Jumperlow** [comment] 2022-04-09 16:10
Hey, @jordansexton, any idea when you guys have time to release this? Or is there a workaround (combination of older versions/..)? I'm currently stuck with a project due to this bug.

**Comment by felipecsl** [comment] 2022-04-14 19:27
I was able to work around the type errors by creating a typescript file on my project with the following contents
```typescript
declare module "buffer-layout";

// https://github.com/solana-labs/solana-program-library/issues/2534
// Remove this workaround when a new version of @solana/spl-token is available
declare interface Layout {}
```

**Comment by DB-Vincent** [comment] 2022-04-15 17:38
> I was able to work around the type errors by creating a typescript file on my project with the following contents
> 
> ```ts
> declare module "buffer-layout";
> 
> // https://github.com/solana-labs/solana-program-library/issues/2534
> // Remove this workaround when a new version of @solana/spl-token is available
> declare interface Layout {}
> ```

Could you elaborate on this? Where did you create the file? I've put this in `node_modules/@solana/buffer-layout/src/Layout.ts` but I get the same error.

**Comment by Jumperlow** [comment] 2022-04-15 17:40
> I was able to work around the type errors by creating a typescript file on my project with the following contents
> 
> ```ts
> declare module "buffer-layout";
> 
> // https://github.com/solana-labs/solana-program-library/issues/2534
> // Remove this workaround when a new version of @solana/spl-token is available
> declare interface Layout {}
> ```

@felipecsl Could you elaborate on this? Where did you create the file? I've put this in `node_modules/@solana/buffer-layout/src/Layout.ts` but I get the same error.

**Comment by felipecsl** [comment] 2022-04-15 17:41
Put this file in your project source tree, eg under `src/`, assuming that's where your code lives

**Comment by israelidanny** [comment] 2022-04-18 13:40
I mean, since this is merged - all those quick hacks aren't necessary, are they? @jordansexton any ETA on when this lands on NPM?

**Comment by Jumperlow** [comment] 2022-04-25 16:37
> Put this file in your project source tree, eg under `src/`, assuming that's where your code lives

I got that figured out, but it doesn't really fix my issue. Still having the following error. Any ideas?
![image](https://user-images.githubusercontent.com/36135315/165134121-a2250c9d-7a15-413d-b27f-0ed861ba8cbc.png)
