### ISSUE TITLE
token-lending: Input token mint account is not valid

### ISSUE THREAD

**Issue by leonardgee** [solana-labs/solana-program-library#1697] opened 2021-05-11 10:31 UTC
On test net, I have been hitting the following error when calling `initReserve` instruction:

```
"Program log: loading quote token mint AcFStaPiSSSTTzYBVv3WXewtpgCiFF3zU3tG95HkhCcm", "Program log: Input token mint account is not valid", "Program 7cFfVGp6mAtBFsjp5GtjHZjLJEDdfEnG2QfuVUUeyGrY consumed 23512 of 200000 compute units"
```

It says the account `AcFStaPiSSSTTzYBVv3WXewtpgCiFF3zU3tG95HkhCcm` is not valid token account. However, I check the block explorer [here](https://explorer.solana.com/address/AcFStaPiSSSTTzYBVv3WXewtpgCiFF3zU3tG95HkhCcm?cluster=testnet). The token account does exist. I am not sure what went wrong also since [this](https://explorer.solana.com/tx/5p1hRu2oAyfyt438mxiseTorNp11oepQriFwu1GiyeDjM3CuaKbpfe2TCoXwTFfj1tGFunkb3Fuwd9TSiBQucVr?cluster=testnet) transaction is successful...

**Comment by jordansexton** [comment] 2021-06-08 01:27
Closing since quote SPL token mints are no longer used with Pyth @ #1757. Please reopen if there's another reason the issue is relevant though.

**Closed by jordansexton** 2021-06-08 01:27 UTC

**Comment by jordansexton** [comment] 2021-06-08 01:29
Also just to note, if the original issue was encountered while using the testnet version of the deployed lending program, that program hasn't been working for some time (since Serum V3).
