### ISSUE TITLE
@solana/spl-token@0.4.7 causing ESM import errors

### ISSUE THREAD

**Issue by y0unghe** [solana-labs/solana-program-library#6990] opened 2024-07-08 18:52 UTC
I am trying to deploy the codes to Vercel serverless. I got the following errors:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /var/task/node_modules/@solana/spl-token/lib/cjs/index.js from /var/task/src/core/web3.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /var/task/node_modules/@solana/spl-token/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
at /opt/rust/nodejs.js:1:11508
at Function.$t (/opt/rust/nodejs.js:1:11878)
at K.e.<computed>.J._load (/opt/rust/nodejs.js:1:11478)
at Object.<anonymous> (/var/task/src/core/web3.js:12:21) {
code: 'ERR_REQUIRE_ESM'
}
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
INIT_REPORT Init Duration: 1115.37 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
Error [ERR_REQUIRE_ESM]: require() of ES Module /var/task/node_modules/@solana/spl-token/lib/cjs/index.js from /var/task/src/core/web3.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /var/task/node_modules/@solana/spl-token/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
at /opt/rust/nodejs.js:1:11508
at Function.$t (/opt/rust/nodejs.js:1:11878)
at K.e.<computed>.J._load (/opt/rust/nodejs.js:1:11478)
at Object.<anonymous> (/var/task/src/core/web3.js:12:21) {
code: 'ERR_REQUIRE_ESM'
}
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
INIT_REPORT Init Duration: 1913.41 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
```

**Comment by buffalojoec** [comment] 2024-07-08 19:33
Thanks, duplicate of #6958.

**Closed by buffalojoec** 2024-07-08 19:33 UTC
