### ISSUE TITLE
[token/ts] TypeError: fields must be array of Layout instances

### ISSUE THREAD

**Issue by Admdebian** [solana-labs/solana-program-library#2683] opened 2021-12-30 09:30 UTC
If I import the library I get:

    TypeError: fields must be array of Layout instances

NPM package:
    

    @solana/spl-token: ^0.2.0-alpha.0

https://github.com/solana-labs/solana-program-library/blob/c5d73812cb2df5f2e71e832f70da7af90604b085/token/ts/src/instructions/initializeMint.ts#L22-L29

# Update
The problem disappear if I install:

    npm install -S @solana/buffer-layout

NPM package:

    @solana/buffer-layout: ^4.0.0

Maybe it's an npm dependencies resolution problem.

**Comment by jordansexton** [comment] 2021-12-30 15:18
Hmm

https://github.com/solana-labs/solana-program-library/blob/c5d73812cb2df5f2e71e832f70da7af90604b085/token/ts/package.json#L42

The package declares that dependency. Can you post your package.json?

**Comment by Admdebian** [comment] 2021-12-30 16:00
{
      "name": "MyProject",
      "version": "1.0.0",
      "private": true,
      "description": "",
      "main": "index.js",
      "scripts": {
        "test": "jest",
        "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
      },
      "keywords": [
        "blockchain"
      ],
      "author": "Admdebian",
      "license": "ISC",
      "devDependencies": {
        "@babel/core": "^7.16.0",
        "@babel/preset-env": "^7.16.4",
        "@babel/preset-flow": "^7.16.0",
        "@babel/runtime": "^7.16.3",
        "@types/bs58": "^4.0.1",
        "@types/jest": "^27.0.2",
        "babel-jest": "^27.3.1",
        "babel-plugin-transform-async-to-generator": "^6.24.1",
        "eslint": "^8.2.0",
        "jest": "^27.3.1",
        "metro-react-native-babel-preset": "^0.66.2",
        "tslint": "^6.1.3",
        "typescript": "^4.4.4"
      },
      "jest": {
        "transform": {
          "^.+\\.[t|j]sx?$": "babel-jest"
        },
        "moduleFileExtensions": [
          "ts",
          "tsx",
          "js",
          "jsx",
          "json",
          "node"
        ]
      },
      "files": [
        "/src"
      ],
      "dependencies": {
        "@bonfida/spl-name-service": "^0.1.22",
        "@project-serum/serum": "^0.13.60",
        "@pythnetwork/client": "^2.5.1",
        "@solana/buffer-layout": "^4.0.0",
        "@solana/spl-token": "^0.2.0-alpha.0",
        "@solana/web3.js": "^1.30.2",
        "bip39": "^3.0.4",
        "bs58": "^4.0.1",
        "ed25519-hd-key": "^1.2.0"
      }
    }

**Comment by Admdebian** [comment] 2021-12-30 16:02
> Hmm
> 
> https://github.com/solana-labs/solana-program-library/blob/c5d73812cb2df5f2e71e832f70da7af90604b085/token/ts/package.json#L42
> 
> The package declares that dependency. Can you post your package.json?

Yes, the dependency is correct. My project requires that I save the dependency in the main package.json

**Comment by jordansexton** [comment] 2021-12-30 19:08
It would help to see your entire project. The error here (`TypeError: fields must be array of Layout instances`) doesn't give enough context, as I can't tell where it's coming from.

**Comment by Admdebian** [comment] 2021-12-30 20:14
> It would help to see your entire project. The error here (`TypeError: fields must be array of Layout instances`) doesn't give enough context, as I can't tell where it's coming from.

I made a new project with only a sample code and the problem disappeared. I think is not related with this library.

Sorry. Thanks for your time!

**Comment by kb24x7** [comment] 2022-02-02 09:08
Having this issue myself now with the latest `@solana/pay` library.

**Comment by rez-cpu** [comment] 2022-02-13 02:44
> 

Its the package version, this is what current combo that works:
    "@solana/pay": "^0.1.3",
    "@solana/spl-token": "^0.2.0-alpha.1",
    "@solana/buffer-layout": "^4.0.0",
    "@solana/web3.js": "^1.34.0",

**Comment by scottwilson312** [comment] 2022-03-04 19:10
```    "@solana/spl-token": "^0.2.0",
    "@solana/buffer-layout": "^4.0.0",
    "@solana/wallet-adapter-base": "^0.9.3",
    "@solana/wallet-adapter-react": "^0.15.3",
    "@solana/wallet-adapter-react-ui": "^0.9.5",
    "@solana/wallet-adapter-wallets": "^0.15.2",
    "@solana/web3.js": "^1.35.1"
```

I have this built and after rebuilding from troday, I got the above error. The fix above worked for me, putting buffer-layout in package.json :+1:

**Comment by wedvjin** [comment] 2022-03-05 19:08
i used yarn instead of npm to install dependencies on a clean project and it worked
```
"dependencies": {
        "@project-serum/anchor": "^0.22.1",
        "@solana/buffer-layout": "^4.0.0",
        "@solana/spl-token": "^0.2.0",
        "@solana/web3.js": "^1.34.0"
    },
```

**Comment by thedonmon** [comment] 2022-03-07 04:14
I'm running into this same issue when calling any of the spl functions. 

```
    const walletAta = await spl.getAssociatedTokenAddress(new PublicKey(mint), walletKeyPair.publicKey, false, spl.TOKEN_PROGRAM_ID, spl.ASSOCIATED_TOKEN_PROGRAM_ID);
    const escrowAta = await spl.getAssociatedTokenAddress(new PublicKey(mint), escrowPaymentAccount, false, spl.TOKEN_PROGRAM_ID, spl.ASSOCIATED_TOKEN_PROGRAM_ID);
```

```

"dependencies": {
        "@project-serum/anchor": "^0.22.1",
        "@solana/buffer-layout": "^4.0.0",
        "@solana/spl-token": "^0.2.0",
        "@solana/web3.js": "^1.34.0"
    },
```

**Comment by jordansexton** [comment] 2022-03-22 19:49
@straversi I've reopened. Please provide a complete, clear reproduction of the issue. So far all we've got to go on is 8 different code snippets, which is kind of impossible to debug.

FWIW, we use `@solana/spl-token` in Solana Pay and we don't need to import `@solana/buffer-layout`, so I'm skeptical that's the actual issue. Dependency issues like this sometimes come from how the dependencies are installed or what the build tooling and config is (Create React App, Webpack, Babel, esbuild, etc)

**Comment by straversi** [comment] 2022-03-22 21:05
Of course, thank you!

```
echo '{
  "name": "spl-repro",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@metaplex-foundation/mpl-token-metadata": "1.2.4",
    "@solana/spl-token": "0.2.0",
    "@solana/web3.js": "1.30.2"
  }
}
' > package.json
npm i
# I'm running node v14.18.2
node
> require('@solana/spl-token');
```

That's all it takes for me.

**Comment by jordansexton** [comment] 2022-03-22 21:11
Thanks! Do you get the same issue when installing with yarn?

**Comment by charlie-amihan** [comment] 2022-03-22 22:13
I am getting the same issue with npm install, yarn install solves the issue for me.

**Comment by steveluscher** [comment] 2022-03-23 02:18
Yeah, this is unfortunate. Sorry folks.

Basically when `npm` lays out the dependency tree, it ends up looking like this.

![image](https://user-images.githubusercontent.com/13243/159609177-aaded27a-ecc1-4e71-90d0-dbd9b77863ac.png)

`spl-token` and the root package each end up with their own copy of `buffer-layout`.

Next, `initializeMint` tries to make use of `buffer-layout-utils` which again has its own copy of `buffer-layout` in it.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/13243/159610329-5bc88270-8f10-4c1c-b38e-a4acd32a304e.png">

By the time these instances of `Layout` – all constructed from different packages of JavaScript – make their way to `node_modules/@solana/spl-token/node_modules/@solana/buffer-layout/lib/Layout.js`, this `instanceof` check fails.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/13243/159610532-ac4de546-3041-41d8-810a-d8519ddc5f0a.png">

You know, and I know, that those values are instances of `Layout`, but since they didn't come from _literally_ the same class, they will never pass an `instanceof` check.

I'll have a think on this.

**Comment by steveluscher** [comment] 2022-03-23 02:31
If someone gets there before I do tomorrow, the answer is going to have something to do with carefully setting [`peerDependencies`](https://stackoverflow.com/a/46630766/802047) in various `package.json` files.

**Comment by steveluscher** [comment] 2022-03-23 02:31
Another thing we might consider, one day, is reimplementing this not to depend on classes, but rather tagged data structures.

```
// Instead of...
new Float(...)

// Do...
float(...)

// Which produces not an instance of a class, but rather a tagged object…
{__type: 'float', ...}
```

No classes, no instances, no problems.

**Comment by steveluscher** [comment] 2022-03-23 21:40
After a few hundred `npm link` backflips, I figured out a short-term fix for this. We're going to have to upgrade `buffer-layout` in unison (https://github.com/solana-labs/solana/pull/23897) and republish Every Package™. Stay tuned.

**Comment by steveluscher** [comment] 2022-03-30 16:03
Upgrade @solana/web3.js in your `package.json` to 1.37.0 and the `fields must be array of Layout instances` error should go away.

Namely, @straversi's example above works for me when I do that. https://github.com/solana-labs/solana-program-library/issues/2683#issuecomment-1075638612

**Comment by steveluscher** [comment] 2022-03-30 16:27
Feel free to reopen this if your problems still persist. Closing for now.

**Closed by steveluscher** 2022-03-30 16:27 UTC

**Comment by Henry-E** [comment] 2022-04-27 11:38
> I'm having this same issue while attempting to use the 0.2.0 `createMint` function in an anchor test (anchor test ends up running `yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts`).

This worked for me but I had to also delete package-lock.json

**Comment by mschneider** [comment] 2022-05-03 09:04
> After a few hundred `npm link` backflips, I figured out a short-term fix for this. We're going to have to upgrade `buffer-layout` in unison ([solana-labs/solana#23899](https://github.com/solana-labs/solana/pull/23899)) and republish Every Package™. Stay tuned.

@steveluscher I saw similar issues with BN js previously. Did you consider to re-export the whole buffer-layout package in web3? This way there's a sure fire way to access the "correct" version in downstream code. Not sure of the drawbacks and longterm issues related to this approach, but it is what anchor does fyi:

https://github.com/project-serum/anchor/blob/master/ts/src/index.ts#L5

**Comment by steveluscher** [comment] 2022-05-03 17:06
Oof. The fact that Anchor re-exports all of web3.js is actually pretty troublesome until I finish https://github.com/solana-labs/solana/issues/20673.

**Comment by WrRaThY** [comment] 2022-05-03 23:39
started happening to me after I updated anchor js to 0.24.2

**Comment by keitaj** [comment] 2022-05-14 10:24
> started happening to me after I updated anchor js to 0.24.2

I happened too but I updated @solana/web3.js and @solana/spl-token and the error did not happen.

```
 "dependencies": {
    "@project-serum/anchor": "^0.24.2",
    "@project-serum/serum": "0.13.61",
    "@solana/buffer-layout": "^4.0.0",
    "@solana/spl-token": "^0.2.0",
    "@solana/web3.js": "^1.41.10",
    "@types/chai": "^4.3.1"
  },
```

**Comment by karan-ksrk** [comment] 2022-07-30 07:20
These Two Combination works for me 
```
 },
  "dependencies": {
    "@solana/buffer-layout": "^3.0.0",
    "@solana/web3.js": "^1.41.10",
  },
```

**Comment by h4rkl** [comment] 2022-08-18 05:50
If you're using yarn you can specify child dependancy resolutions in your package.json file using:

```
  "resolutions": {
    "@solana/buffer-layout": "^4.0.0"
  },
```

NPMs equivalent is overrides - https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

**Comment by ExoticCoder16** [comment] 2022-09-26 07:55
> Upgrade @solana/web3.js in your `package.json` to 1.37.0 and the `fields must be array of Layout instances` error should go away.
> 
> Namely, @straversi's example above works for me when I do that. [#2683 (comment)](https://github.com/solana-labs/solana-program-library/issues/2683#issuecomment-1075638612)

Yes ! Just by typing is not enough, I just re-install solana web3.js package ( npm install --save @solana/web3.js ), it works instantly ! Thank you !

**Comment by georgiod9** [comment] 2022-11-25 11:30
> s, the dependency is correct. My project requires t

I have stumbled upon the same issue, and have also deduced that the problem stems from the duplicity of that same package in 3 places.

**Comment by georgiod9** [comment] 2022-11-25 11:31
> `spl-token` and the root package each end up with their own copy of `buffer-layout`.

I have stumbled upon the same issue, and have also deduced that the problem stems from the duplicity of that same package in 3 places.

**Comment by zsyborg** [comment] 2023-06-02 06:09
rekt, this issue troubling in 2023 too, same old thing, tried yarn, npm, pnpm. Tried reordering the packages in package.json
this issuede my existing running project. Critical Issue

**Comment by reza2870** [comment] 2024-02-12 18:29
> "@metaplex-foundation/mpl-token-metadata": "1.2.4",

Yes
I did all ways
Didn't work for me
